export const MOCK_HOLDINGS = [
  {
    id: "pos_1",
    symbol: "SOL",
    name: "Solana",
    type: "perp",
    side: "long",
    leverage: 5,
    quantity: 55.2, 
    entryPrice: 88.50,
    price: 98.80, 
    liquidationPrice: 70.80,
    fees: 1.25, 
    pnl: 457.16,
    pnlPercent: 14.6,
    value: 5734.56,
  },
  {
    id: "pos_2",
    symbol: "JUP",
    name: "Jupiter",
    type: "perp",
    side: "short",
    leverage: 10,
    quantity: 1500,
    entryPrice: 1.25,
    price: 1.18,
    liquidationPrice: 1.45,
    fees: 4.50,
    pnl: 150.00,
    pnlPercent: 5.6,
    value: 1700.00,
  },
  {
    id: "pos_3",
    symbol: "BONK",
    name: "Bonk",
    type: "perp",
    side: "long",
    leverage: 20,
    quantity: 59000000,
    entryPrice: 0.000021,
    price: 0.000024,
    liquidationPrice: 0.000019,
    fees: 0.85,
    pnl: 172.00,
    pnlPercent: 14.2,
    value: 1100.00,
  },
  {
    id: "pos_4",
    symbol: "WIF",
    name: "dogwifhat",
    type: "perp",
    side: "long",
    leverage: 2,
    quantity: 300,
    entryPrice: 2.80,
    price: 2.65,
    liquidationPrice: 1.10,
    fees: 0.40,
    pnl: -35.00,
    pnlPercent: -3.3,
    value: 325.00,
  },
];

export const DEFAULT_AI_RESPONSE = {
  tradingVenue: "Deriverse V2 (Solana)",
  marketNews: "Bullish divergence on 4H chart. Funding rates represent high demand for longs.",
  riskAssessment: "Moderate. SOL exposure is high relative to portfolio size. Consider hedging with JUP shorts.",
};